name: Jalankan Tes Cypress

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Clear npm cache (opsional tapi direkomendasikan untuk debug)
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Debug check-more-types (opsional untuk cek dependensi)
        run: ls -la node_modules/check-more-types || echo "check-more-types tidak ditemukan"

      - name: Verifikasi instalasi Cypress
        run: npx cypress verify

      - name: Jalankan tes Cypress
        run: npx cypress run
