name: Jalankan Tes Cypress

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Fix Cypress binary permissions
        run: chmod +x node_modules/.bin/cypress

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Jalankan tes Cypress
        run: npx cypress run
